config/routes.rb
Whisper::Application.routes.draw do
  
  resources :groups
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :memberships, only: [:create, :destroy]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/since',   to: 'static_pages#since',   via: 'get'
  match '/search',  to: 'static_pages#search',  via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/groups/:id/since',   to: 'groups#since',             via: 'post'
  match '/groups/:id/infinite',to: 'groups#infinite',             via: 'post'

  resources :posts

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :reverse_memberships, foreign_key: "group_id",
                                   class_name:  "Membership",
                                   dependent:   :destroy
    has_many :users, through: :reverse_memberships, source: :user
   	has_many :posts
   	has_many :comments, through: :posts

   	validates :name,
  	:presence => true,
  	length: { minimum: 1 }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :since, :infinite]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if signed_in? and current_user.following?(@group)
      @membership = current_user.following?(@group)
      if @membership
        @new_posts = @group.posts.where("created_at > :update", {:update => @membership.last_view})
        @membership.last_view = Time.now
        @membership.save

        @new_posts.each do |post|
          @membership.posts << post
        end
      end
    end
    if signed_in?
      @comment = current_user.comments.build
      @post = current_user.posts.build
    else
      @comment = User.find(1).comments.build # anonymous user
      @post = User.find(1).posts.build
    end 
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def since
    if signed_in? and @current_user.following?(@group) #unnecessary, but will allow for read receipts later
        @membership = current_user.following?(@group)
        @posts = @group.posts.where("posts.created_at > :update", {:update => @membership.last_view})
        @comments = @group.comments.where("comments.updated_at > :update AND comments.user_id != :user", {:update => @membership.last_view, :user => current_user.id})

        unless @posts.empty? and @comments.empty?
          @membership.last_view = Time.now
          @membership.save
        end
    else # Need to use other method for anonymous users
      @posts = @group.posts.where("posts.created_at > :timestamp", {:timestamp => DateTime.strptime(params[:ts], "%s")})
      @comments = @group.comments.where("comments.updated_at > :timestamp", {:timestamp => DateTime.strptime(params[:ts], "%s")})
    end

    if signed_in?
      @comment = current_user.comments.build
    else
      @comment = User.find(1).comments.build
    end

    @last_update = Time.now.to_i

    respond_to do |format|
      format.js
    end

  end

  
  def infinite
    @comment = current_user.comments.build if signed_in?
    @start = group_params[:start].to_i
    @posts = @group.posts[@start..-1].take(8)

    respond_to do |format|
      format.js
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        if signed_in?
          current_user.follow!(@group)
        end

        format.html {
          flash[:success] = "Group was successfully created!"       
          redirect_to @group }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :start, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_feed.html.erb
<div class="col-xs-12 col-sm-3 pull-right">
  <div class="jumbotron">
    <h3><%= @group.name %></h3>
    <p><%= @group.description %></p>

    <div class="stats">
      <a href="<%= @group %>">
        <strong id="following" class="stat">
          <%= @group.users.count %>
        </strong>
        members
      </a>
      <a href="<%= @group %>">
        <strong id="followers" class="stat">
          <%= @group.posts.count %>
        </strong>
        posts
      </a>
    </div>

    <%= render 'follow_form' if signed_in? %>
  </div>

  <%= form_for(@post, :html => {:class => 'form-horizontal'}) do |f| %>

  <div class="well"> 
                <h4>What's New</h4>
                 <div class="form-group" style="padding:14px;">
                  <%= f.text_area :content, :class => "form-control", placeholder: "Post to " + @group.name %>
                  <div id="uploadsuccess" class="alert alert-success" style="display:none;">File uploaded</div>
                </div>
                <%= f.hidden_field :group_id, :value => @group.id %>
                <%= f.hidden_field :media, :value => "" %>
                <%= f.hidden_field :media_type, :value => "-1" %>
                <%= content_tag :button, :type => :submit, :class => "btn btn-success pull-right" do %>
                Post
                <% end %>
                 <ul class="list-inline">
                  <li id="twitterButton"><a href="#"><%= image_tag 'glyphs/twitter.png', :class => "glyph" %></i></a></li>
                  <li id="instagramButton"><a href="#"><%= image_tag 'glyphs/instagram.png', :class => "glyph" %></a></li>
                  <li id="facebookButton"><a href="#"><%= image_tag 'glyphs/facebook.png', :class => "glyph" %></i></a></li>
                  <li id="uploadButton"><a href="#"><i class="glyphicon glyphicon-upload glyph"></i></a></li>
                </ul>
      </div>
  </div>


<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload a file</h4>
      </div>
      <div class="modal-body">
              <h4>Please select the file you would like to share:</h4>
              <div class="input-group text-center">
              <input id="uploadInput" type="text" class="form-control input-lg" placeholder="Enter your URL address">
                <span class="input-group-btn">
                  
                  <span class="btn btn-default btn-file">Browse<%= f.file_field :image %></span>

                </span>
              </div>
              <div id="previewUpload" class="socialPreview"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary confirmSocial" data-target="#uploadModal">Ok</button>
      </div>
    </div>
  </div>
</div>

<% end %>



<div class="col-xs-12 col-sm-9">
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  <div class="row">
    <div id="contentcol1" class="col-md-6 col-sm-6">
      <% @group.posts.first(3).each do |post| %>
          <%= render post %> 
      <% end %>
    </div>
    <div id="contentcol2" class="col-md-6 col-sm-6">
    <% @group.posts.drop(3).first(3).each do |post| %>
          <%= render post %> 
      <% end %>
    </div>
</div>
<div class="endmarker"></div>
</div>
<div>
<div class="modal fade" id="twitterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Embed a Tweet</h4>
      </div>
      <div class="modal-body">
              <h4>Copy and paste the URL of the Tweet you would like to share:</h4>
              <div class="input-group text-center">
              <input id="twitterInput" type="text" class="form-control input-lg" placeholder="Enter your URL address">
                <span class="input-group-btn"><button id="twitterPreviewButton" class="btn btn-lg btn-primary" type="button"><i class="glyphicon glyphicon-download"></i></button></span>
              </div>
              <div id="previewTweet" class="socialPreview"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary confirmSocial" data-target="#twitterModal">Ok</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="instagramModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Embed an Instagram</h4>
      </div>
      <div class="modal-body">
              <h4>Copy and paste the URL of the Instagram you would like to share:</h4>
              <div class="input-group text-center">
              <input id="instagramInput" type="text" class="form-control input-lg" placeholder="Enter your URL address">
                <span class="input-group-btn"><button id="instagramPreviewButton" class="btn btn-lg btn-primary" type="button"><i class="glyphicon glyphicon-download"></i></button></span>
              </div>
              <div id="previewInstagram" class="socialPreview"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary confirmSocial" data-target="#instagramModal">Ok</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="facebookModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Embed a Facebook post</h4>
      </div>
      <div class="modal-body">
              <h4>Copy and paste the URL of the Facebook post you would like to share:</h4>
              <div class="input-group text-center">
              <input id="facebookInput" type="text" class="form-control input-lg" placeholder="Enter your URL address">
                <span class="input-group-btn"><button id="facebookPreviewButton" class="btn btn-lg btn-primary" type="button"><i class="glyphicon glyphicon-download"></i></button></span>
              </div>
              <div id="previewFacebook" class="socialPreview">
                


              </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary confirmSocial" data-target="#facebookModal">Ok</button>
      </div>
    </div>
  </div>
</div>

</div>
<script>
$(document).ready(function() {
  $.getScript("//platform.twitter.com/widgets.js");
});
</script>

app/views/groups/_follow.html.erb
<%= form_for(current_user.memberships.build(group_id: @group.id)) do |f| %>
  <div><%= f.hidden_field :group_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/groups/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@group) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_unfollow.html.erb
<%= form_for(current_user.memberships.find_by(group_id: @group.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/infinite.js.erb
<% @posts.each do |post| %>
	var posthtml = '<%= j render post %>';
	if($("#contentcol1").height() < $("#contentcol2").height()) {
		$("#contentcol1").append(posthtml);
	} else {
		$("#contentcol2").append(posthtml);
	}
<% end %>

<% if @posts.count == 8 %>
setTimeout(function() {
$(document).scroll(function(e){
    if (element_in_scroll($(".endmarker"))) {
            infinite();
        };
    });

}, 1000);

<% end %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="row">
<% if signed_in? %>
  <div id="sidebar-wrapper" class="col-xs-12 col-md-1">
    <%= render 'shared/sidebar' %>
  </div>
  <div id="main-wrapper" class="col-xs-12 col-md-11 pull-right">
    <%= render 'feed' %>
  </div>
<% else %>
  <div id="main-wrapper" class="col-xs-11">
    <%= render 'feed' %>
  </div>
<% end %>
</div>

<script>

var count = 8
var last_update = Date.now()/1000-10000;

function updates() {
  $.ajax({
          type: "POST",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          url: "/groups/<%= @group.id %>/since",
          data: { "group": {}, "ts": last_update },
      success: function(data) {      
        return false;
      },
      error: function(data) {
        return false;
      }
    });
}

function infinite() {

    if (element_in_scroll($(".endmarker"))) {
            $(document).unbind('scroll');
            $.ajax({
                type: "POST",
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                url: "/groups/<%= @group.id %>/infinite",
                data: { "group" : {start:""+count}}, 
                success: function(data) {    
                  count += 8  
                  return false;
                }
            });
        };
}



function element_in_scroll(elem)
{
    var docViewTop = $(window).scrollTop();
    var docViewBottom = docViewTop + $(window).height();
 
    var elemTop = $(elem).offset().top;
    var elemBottom = elemTop + $(elem).height();
 
    return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
}

$(document).ready(function() {

    $(document).scroll(function(e){
      if (element_in_scroll($(".endmarker"))) {
        e.stopImmediatePropagation();
                infinite();       
        };
    });

    last_update = Date.now()/1000;
    setInterval("updates()", 1000); 

    $(".confirmSocial").click(function() {
      $($(this).data('target')).modal('hide');
      var media = $($(this).data('target')).find('input').val();//$($(this).data('target')).find('.socialPreview').html();
      if(media != "") {
        $("#post_media").val(media);
        $("#post_media_type").val($(this).parents(".modal").index());
      }
      if($("#post_image").val() != "") {
        $("#post_media_type").val(3);
        $("#uploadsuccess").show();
      }


    });


      $(".comments").scrollTop(1000000);


    $("#twitterButton").click(function() {$("#twitterModal").modal();return false;});
    $("#instagramButton").click(function() {$("#instagramModal").modal();return false;});
    $("#facebookButton").click(function() {$("#facebookModal").modal();return false;});
    $("#uploadButton").click(function() {$("#uploadModal").modal();return false;});

    $("#twitterPreviewButton").click(function() {
      $("#previewTweet").html('<blockquote class="twitter-tweet" lang="en"><a href="' + $("#twitterInput").val() + '">March 10, 2014</a></blockquote>');
      $.getScript("//platform.twitter.com/widgets.js");
    });
    $("#instagramPreviewButton").click(function() {
      var match = /(instagram\.com\/p\/\w{10})/.exec($("#instagramInput").val());
      if(match) {
        $("#previewInstagram").html('<iframe src="//' + match[0] + '/embed/" width="490" height="568" frameborder="0" scrolling="no" allowtransparency="true"></iframe>');
      } else {
        $("#previewInstagram").html('<div class="alert alert-warning">Uh-oh, please check your URL!</div>');
      }
    });
    $("#facebookPreviewButton").click(function() {
      var match = /(<div id.+<\/div><\/div>)/.exec($("#facebookInput").val());
      if(match) {
        $("#previewFacebook").html(match[0]);
      } else {
        $("#previewFacebook").html('<div class="alert alert-warning">Uh-oh, please check your URL!</div>');
      }
    });


});
</script>

<!-- Show feed -->
<!-- Post box -->

app/views/groups/since.js.erb
<% @comments.each do |comment| %>
	<% if comment.sticker_id == nil %>
	if($("#comment-<%=comment.id%>").length > 0) {
		$("#comment-<%=comment.id%>").empty()
		$("#comment-<%=comment.id%>").append("<p><%=comment.content%></p>");
		<% comment.secondary_content.each do |secondary| %>
			$("#comment-<%=comment.id%>").append("<p><%=secondary%></p>")
		<% end %>

	} else {
	$('<hr/><div class="comment" style="display:none;"><div><%= image_tag comment.user.avatar(:thumb), :class => "img-circle pull-left" %></div><div><span class="comment_user"><%= comment.user.name %></span><span class="timestamp pull-right"><span class="glyphicon glyphicon-time"></span>1s</span><div id="comment-<%=comment.id%>"><p><%= comment.content %> </p></div><div class="clearfix"></div></div></div>').appendTo($("#post-<%= comment.post.id %>").find('.comments')).show();//.slideDown('fast');
	}

	<% else %>
	$('<hr/><div class="comment" style="display:none;"><div><%= image_tag comment.user.avatar(:thumb), :class => "img-circle pull-left" %></div><div><span class="comment_user"><%= comment.user.name %></span><span class="timestamp pull-right"><span class="glyphicon glyphicon-time"></span>1s</span><div id="comment-<%=comment.id%>"><%= image_tag "stickers/pricklypear" + comment.sticker_id.to_s + ".png" %></div><div class="clearfix"></div></div></div>').appendTo($("#post-<%= comment.post.id %>").find('.comments')).show();//.slideDown('fast');
	<% end %>

	if($("#post-<%= comment.post.id %>").find(".comments").height() >= 300) {
		$("#post-<%= comment.post.id %>").find(".comments_wrap").addClass("comments_wrap_overflow");
	}
	$("#post-<%= comment.post.id %>").find(".comments").scrollTop(1000000);
<% end %>

<% @posts.each do |post| %>
	var posthtml = '<%= j render post %>';
	if($("#contentcol1").height() < $("#contentcol2").height()) {
		$("#contentcol1").prepend(posthtml);
	} else {
		$("#contentcol2").prepend(posthtml);
	}
<% end %>

last_update = '<%= @last_update %>';