config/routes.rb
Whisper::Application.routes.draw do
  
  resources :groups
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :memberships, only: [:create, :destroy]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/since',   to: 'static_pages#since',   via: 'get'
  match '/search',  to: 'static_pages#search',  via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/groups/:id/since',   to: 'groups#since',             via: 'post'
  match '/groups/:id/infinite',to: 'groups#infinite',             via: 'post'

  resources :posts

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :seen_post_trackers

	has_attached_file :image, :styles => { :normal => "350x" }, :default_url => "/images/:style/missing.jpg"

	
	has_many :comments
	belongs_to :user
	validates :user_id, presence: true
	belongs_to :group
	validates :group_id, presence: true
	default_scope -> { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def create
    if signed_in?
      @post = current_user.posts.build(micropost_params)
    else
      @post = User.find(1).posts.build(micropost_params)
    end
    if @post.save
      flash[:success] = "Post created!"
      redirect_to @post.group
    else
      render 'static_pages/home'
    end
  end

  def destroy
    group = @post.group
    if signed_in? and @post.user == current_user
      @post.destroy
    end
    respond_to do |format|
      format.html { redirect_to group }
      format.json { head :no_content }
    end
  end

  def index
    @posts = Post.all
  end
  
  def show
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
    def micropost_params
      params.require(:post).permit(:content, :group_id, :media, :media_type, :image)
    end
end

app/views/posts/_comment_box.html.erb
<div class="comment_well"> 
  <%= form_for(@comment, :html => {:class => 'form-horizontal'}, remote: true) do |f| %>
    <div class="form-group">

      <table border="0" class="commenttable">
        <colgroup>
          <col />
          <col style="width:3em;" span="2" />
        </colgroup>
        <tbody>
          <tr>
            <td><%= f.text_field :content, :autocomplete => "off", placeholder: "Enter your comment here..." %></td>
            <td><button class="btn btn-default pull-right stickerShow" style="font-size:20px;line-height:16px;" type="button" data-container="body" data-postid="<%=post.id%>" data-toggle="popover" data-placement="top" >☺</button></td>
            <td><%= content_tag :button, :type => :submit, :class => "btn btn-success pull-right" do %>
        Post
      <% end %></td>
          </tr>
        </tbody>
      </table>


      </div>
    <%= f.hidden_field :post_id, :value => post.id %>
  <% end %>
</div>

<script>

function lolol(e, p) {
  $.ajax({
          type: "POST",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          url: "/comments",
          data: { "comment": { "post_id": e, "sticker_id": p, "content": "1"} },
      success: function(data) {      
        return false;
      },
      error: function(data) {
        return false;
      }
    });
}


$(document).ready(function() {

  $(".stickerShow").popover({
  html: true,
  trigger: 'click',
  content: function () {   
    return '<img class="sticker" onclick="lolol(' + $(this).data('postid') + ', 1)" src="/images/stickers/pricklypear1.png">' + 
           '<img class="sticker" onclick="lolol(' + $(this).data('postid') + ', 2)" src="/images/stickers/pricklypear2.png">' + 
           '<img class="sticker" onclick="lolol(' + $(this).data('postid') + ', 3)" src="/images/stickers/pricklypear3.png">' +
           '<img class="sticker" onclick="lolol(' + $(this).data('postid') + ', 4)" src="/images/stickers/pricklypear4.png">';
  }
  });


});
</script>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="panel panel-default post">

	<div class="panel-heading">
		<%= link_to 'x', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, :class => "delete pull-right" if signed_in? and post.user == current_user %>
		<h4>		<%= image_tag post.user.avatar(:thumb), :class => "img-circle pull-left" %>
<%= post.user.name %></h4></div>
	<div class="panel-body">
	<div class="media center">
		<% if post.media_type == 0 #twitter %> 
			<blockquote class="twitter-tweet" lang="en"><a href="<%=post.media%>">March 10, 2014</a></blockquote>

		<% elsif post.media_type == 1 #instagram %>
			<% if /(instagram\.com\/p\/\w{10})/.match(post.media) %>
				<iframe src="//<%=/(instagram\.com\/p\/\w{10})/.match(post.media)[0]%>/embed/" width="490" height="568" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
			<% end %>
		<% elsif post.media_type == 2 #facebook %>
			<% if /(<div id.+<\/div><\/div>)/.match(post.media) %>
				<%= raw post.media %>
			<% end %>
		<% elsif post.media_type == 3 #image upload %>
			<%= image_tag post.image(:normal) %>
		<% elsif post.media_type == -1 %>

		<% end %>
	</div>
	<hr/>
	<div class="container"><h4><%= post.content %></h4></div>
	<hr/>
	<% if post.comments.count > 3 %>
		<div class="comments_wrap-scroll comments_wrap_overflow">
	<% else %>
		<div class="comments_wrap">
	<% end %>
	<div class="comments">
	<% post.comments.each do |comment| %>
		<hr/>
		<% if signed_in? and comment.user.id == current_user.id %>
		<div class="comment">
			<div class="container-liquid pull-left">
				<span class="timestamp">
    				<span class="glyphicon glyphicon-time"></span> <%= time_ago_in_words(comment.created_at, :locale => "en") %>
  				</span>

  				<div id="comment-<%= comment.id %>">
  				  	<% if comment.sticker_id == nil %>
						<p><%= comment.content %> </p>
						<% comment.secondary_content.each do |content| %>
							<p><%= content %> </p>
						<% end %>
					<% else %>
						<%= image_tag 'stickers/pricklypear' + comment.sticker_id.to_s + '.png' %>
					<% end %>
				</div>
			</div>
		<%= image_tag comment.user.avatar(:thumb), :class => "img-circle pull-right" %>
			<span class="comment_user pull-right">
				<%= comment.user.name %>
  			</span>

			<div class="clearfix"></div>
		</div>
		<% else %>
		<div class="comment">
		<div>
		<%= image_tag comment.user.avatar(:thumb), :class => "img-circle pull-left" %>
		</div>
		<div>
			<span class="comment_user">
			<%= comment.user.name %>
			</span>
			<span class="timestamp pull-right">
    			<span class="glyphicon glyphicon-time"></span> <%= time_ago_in_words(comment.created_at, :locale => "en") %>
  			</span>
  			<div id="comment-<%= comment.id %>">
				<% if comment.sticker_id == nil %>
						<p><%= comment.content %> </p>
						<% comment.secondary_content.each do |content| %>
							<p><%= content %> </p>
						<% end %>
					<% else %>
						<%= image_tag 'stickers/pricklypear' + comment.sticker_id.to_s + '.png' %>
					<% end %>
			</div>
			<div class="clearfix"></div>
			</div>
			</div>
		<% end %>
	<% end %>
	</div>
	</div>
	</div>
	<div class="panel-footer">
    	<%= render 'posts/comment_box', :post => post %>
	</div>
</div>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', '#' %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>