config/routes.rb
Whisper::Application.routes.draw do
  
  resources :groups
  resources :users
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :memberships, only: [:create, :destroy]

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/since',   to: 'static_pages#since',   via: 'get'
  match '/search',  to: 'static_pages#search',  via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/groups/:id/since',   to: 'groups#since',             via: 'post'
  match '/groups/:id/infinite',to: 'groups#infinite',             via: 'post'

  resources :posts

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.goatse.fr/">Whispr</a>
    by Lawl Co
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://www.goatse.fr">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="header" class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <i class="icon-reorder"></i>
        </button>
        <%= link_to "Whispr", root_path, class: "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li>
                <%= link_to "Home", root_path %>
            </li>
 
        <!--    <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Navbar Item 2<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Navbar Item2 - Sub Item 1</a></li>
                </ul>
            </li>-->
            <li>
                <%= link_to "Help", help_path %>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
        <li>
        <div class="search">
            <%= form_tag("/search", method: "get") do %>
                <%= text_field_tag :q, nil, :autocomplete => "off" %>
                <%= content_tag :button, :type => :submit, :class => "" do %>
                    <i class="glyphicon glyphicon-search"></i>
                <% end %>
            <% end %>
            <ul id="autocomplete">
            </ul>
        </div>
        </li>
        <% if signed_in? %>
            <li class="dropdown">
                <a href="#" id="nbAcctDD" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>
                <%= image_tag current_user.avatar(:thumb), :class => "img-circle" %>

                <%= current_user.name %><i class="icon-sort-down"></i></a>
                <ul class="dropdown-menu pull-right">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
    </nav>
</div>

<script>

function instaSearch(query) {
    if($("#q").val() == "") {
        $("#autocomplete").empty();
    } else {
    $.ajax({
          type: "GET",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          url: "/search",
          data: { "q": $("#q").val() },
      success: function(data) {      
        return false;
      },
      error: function(data) {
        return false;
      }
    });
    }
}

$(document).ready(function() {
    $(".search input").keydown(function(e) {
        if(e.keyCode == 9 || e.keyCode == 40 || e.keyCode == 38 || e.keyCode == 13) {
            if((e.keyCode == 13 || e.keyCode == 9) && $(".acselected").length != 0) {
                window.location.href = $(".acselected").find("a").attr('href');
            }
            if(!(e.keyCode == 13 && $(".acselected").length == 0)) {
                e.preventDefault();
                e.stopImmediatePropagation();
            }
            if($("#autocomplete").children().length > 0) {
                if(e.keyCode == 40) {
                    if($(".acselected").length == 0) {
                        $("#autocomplete").children().first().addClass("acselected");
                    } else {
                        if($("#autocomplete").children().length - $(".acselected").index() > 1) {
                            $($("#autocomplete").children()[$(".acselected").removeClass("acselected").index()+1]).addClass("acselected");
                        }
                    }
                }
                if(e.keyCode == 38) {
                    if($(".acselected").index() == 0) {
                        $(".acselected").removeClass("acselected");
                    } else {
                        $($("#autocomplete").children()[$(".acselected").removeClass("acselected").index()-1]).addClass("acselected");
                    }
                }
            }
        }
    });
    $(".search input").keyup(function(e) {
         if(e.keyCode != 40 && e.keyCode != 38) 
            instaSearch();
        
    });
});

</script>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-wrapper" class="col-xs-12 col-md-1">
    <div id="sidebar">
        <ul class="nav list-group">
            <% current_user.groups.each do |group| %>
                <li class="list-group-item">
                <div class="sidebar_group_thumb">
                  <table>
                  <tr>
                    <td><%= image_tag group.users.last.avatar(:thumb), :class => "img-circle pull-left" %></td>
                    <td><%= image_tag group.users.last.avatar(:thumb), :class => "img-circle pull-left" %></td>
                  </tr>
                  <tr>
                    <td><%= image_tag group.users.last.avatar(:thumb), :class => "img-circle pull-left" %></td>
                    <td>1</td>
                  </tr>
                  </table>
                </div>
                  <%= link_to group.name, group %>
                </li>
            <% end %>
            <li id="new_group_sidebar"><a href="#" class="list-group-item"><i class="glyphicon glyphicon-plus glyph"></i></a></li>
        </ul>
    </div>
</div>

<script>
$(document).ready(function() {
    $("#new_group_sidebar a").click(function() {$("#newGroupModal").modal();return false;});
});
</script>

<div class="modal fade" id="newGroupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
   <%= form_for(Group.new) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create a group</h4>
      </div>

      <div class="modal-body">
            <h4>Enter a name for your group:</h4>
              <div class="input text-center">
                <%= f.text_field :name, :class => "form-control input-lg" %>
              </div>
              <h4>Enter a description for your group:</h4>
              <div class="input text-center">
                <%= f.text_field :description , :class => "form-control input-lg"%>
              </div>
              <h4>Select people to invite:</h4>

              <div class="well well-lg">
              </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Ok</button>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whisper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div id="wrapper"> # needed for sidebar
  <div id="main" >
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>
</body>
</html>